# Project 1 - Part II: Data Science with NumPy & Pandas
# MATH 014 - Introduction to Data Science
# Student Name: Godfred Asamoah 
# Student ID: @03054184  
# Due Date: 03-21-2025

## Part 1: Understanding NumPy & Pandas

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

### TASK 1: NUMPY BASICS

#### 1.1 Numpy Array Creation

In [8]:
# 1D Numpy array of ints from 1 - 20
array_1d = np.arange(1, 21)
print("1D array of integers from 1 to 20:")
print(array_1d)

1D array of integers from 1 to 20:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [10]:
# 2D Numpy array (5x4) filled with random numbers 
array_2d = np.random.random((5, 4))
print("\2D array (5x4) of random nums:")
print(array_2d)

D array (5x4) of random nums:
[[0.55819402 0.42807249 0.71645839 0.55550102]
 [0.26618682 0.05665466 0.51624707 0.37177895]
 [0.4489265  0.26396615 0.88703869 0.03521425]
 [0.49634035 0.31259991 0.75335523 0.4153651 ]
 [0.20677948 0.96260964 0.27191062 0.52292157]]


#### 1.2 Array Indexing & Slicing

In [13]:
# Extract even nums from 1D array
even_nums = array_1d[array_1d % 2 == 0]
print("\n Even nums from 1D array:")
print(even_nums)


 Even nums from 1D array:
[ 2  4  6  8 10 12 14 16 18 20]


In [15]:
# Extract 2nd & 4th row from 2D array
second_fourth_rows = array_2d[[1, 3], :]
print("\n2nd & 4th rows from 2D array:")
print(second_fourth_rows)


2nd & 4th rows from 2D array:
[[0.26618682 0.05665466 0.51624707 0.37177895]
 [0.49634035 0.31259991 0.75335523 0.4153651 ]]


#### 1.3 Mathematical Operations

In [18]:
# Numpy array of nums from 10 - 100 with step 10
array_10step = np.arange(10, 101, 10)
print("\nArray with step of 10 from 10 - 100:")
print(array_10step)


Array with step of 10 from 10 - 100:
[ 10  20  30  40  50  60  70  80  90 100]


In [20]:
# Element-wise square and square root ops on array
array_squared = np.square(array_10step)
array_sqrt = np.sqrt(array_10step)
print("\nSquared array:")
print(array_squared)
print("\nSquare root of array:")
print(array_sqrt)


Squared array:
[  100   400   900  1600  2500  3600  4900  6400  8100 10000]

Square root of array:
[ 3.16227766  4.47213595  5.47722558  6.32455532  7.07106781  7.74596669
  8.36660027  8.94427191  9.48683298 10.        ]


#### 1.4 Statistical Operations

In [23]:
# 3x3 NumPy array of random integers between 1 and 50
array_3by3 = np.random.randint(1, 51, size=(3, 3))
print("\3by3 array of random ints between 1 and 50:")
print(array_3by3)

by3 array of random ints between 1 and 50:
[[44 33 49]
 [37 16 32]
 [ 2 19 47]]


# Mean, median & standard deviation

In [43]:
mean_val = np.mean(array_3by3)
median_val = np.median(array_3by3)
std_val = np.std(array_3by3)

print(f"\nMean: {mean_val}")
print(f"\nMdian: {median_val}")
print(f"\nStandard Deviation: {std_val}")


Mean: 31.0

Mdian: 33.0

Standard Deviation: 14.907119849998598


### TASK 2: PANDAS BASICS

#### 2.1 Data Loading & Overview

In [47]:
# Load the dataset
df = pd.read_csv('project1_part2_data.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'project1_part2_data.csv'

In [ ]:
# First 5 rows
print("\nFirst 5 rows of dataset:")
print(df.head())

In [ ]:
# Dataset info and missing values check
print("\nDataset info:")
print(df.info())

print("\nMissing values per column:")
print(df.isnull().sum())

In [41]:
# Original data copy
df_new = df.copy()

NameError: name 'df' is not defined

#### 2.2 Data Selection & Filtering

In [39]:
# name and salary columns
name_salary_df = df_new[['Name', 'Salary']]
print("\nName and Salary columns:")
print(name_salary_df)

NameError: name 'df_new' is not defined

In [37]:
# employees earning more than $50,000
high_earners_50k = df_new[df_new['Salary'] > 50000]
print("\nEmployees earning more than $50,000:")
print(high_earners_50k)

NameError: name 'df_new' is not defined

#### 2.3 Data Aggregation

In [42]:
# average salary of employees 
avg_salary = df_new['Salary'].mean()
print(f"\nAverage salary of employees: ${avg_salary:.2f}")


,Average salary of employees: $82143.47


In [46]:
# number of employees in each department
dept_count = df_new['Department'].value_counts()
print("\nNumber of employees in each department:")
print(dept_count)


,Number of employees in each department:
,Department
,HR            5
,Operations    4
,Sales         4
,Finance       3
,IT            2
,Marketing     2
,Name: count, dtype: int64


#### 2.4 Data Cleaning

In [68]:
# replacing missing salary values with mean salary
df_new['Salary'] = df_new['Salary'].fillna(df_new['Salary'].mean())

# drop rows with missing ages
df_new.dropna(subset=['Age'], inplace=True)

print("\nData after cleaning:")
print(df_new)
print("\nMissing values after cleaning:")
print(df_new.isnull().sum())


,Data after cleaning:
,    ID               Name   Age         Salary  Department     Position  \
,0    1      Alice Johnson  49.0   46910.000000  Operations   Consultant   
,1    2      Michael Smith  28.0   40206.000000          IT      Manager   
,2    3      Emma Williams  30.0   63419.000000       Sales      Analyst   
,3    4        David Brown  29.0   90636.000000          HR    Executive   
,4    5       Olivia Jones  33.0   82143.473684   Marketing   Consultant   
,5    6       James Garcia  55.0   94268.000000     Finance  Coordinator   
,6    7    Sophia Martinez  54.0   58141.000000  Operations      Manager   
,7    8  Benjamin Anderson  44.0  111910.000000   Marketing      Manager   
,8    9   Charlotte Thomas  45.0   96044.000000       Sales    Executive   
,10  11      Amelia Taylor  56.0   73827.000000  Operations   Consultant   
,11  12      Matthew Moore  43.0   95820.000000     Finance  Coordinator   
,12  13       Isabella Lee  48.0  102623.000000          IT      

### TASK 3: COMBINED NUMPY & PANDAS OPERATIONS

#### 3.1 Converting a Column to a NumPy Array

In [54]:
# extracted salary column as numpy array
salary_array = df_new['Salary'].to_numpy()
print("\nSalary column as NumPy array:")
print(salary_array)


,Salary column as NumPy array:
,[ 46910.          40206.          63419.          90636.
,  82143.47368421  94268.          58141.         111910.
,  96044.          73827.          95820.         102623.
, 115450.          62299.          83585.         104044.
,  82557.          89080.          42693.        ]


In [58]:
# standard deviation of salary array using numpy
salary_std = np.std(salary_array)
print(f"\nStandard deviation of salaries: ${salary_std:.2f}")


,Standard deviation of salaries: $22310.35


#### 3.2 New Column Creation

In [60]:
# new column where each employee gets a 10% increase in salary
df_new['Salary_Bonus'] = df_new['Salary'] * 1.1 
print("\ndata with Salary_Bonus column:")
print(df_new[['Name', 'Salary', 'Salary_Bonus']])


,data with Salary_Bonus column:
,                 Name         Salary   Salary_Bonus
,0       Alice Johnson   46910.000000   51601.000000
,1       Michael Smith   40206.000000   44226.600000
,2       Emma Williams   63419.000000   69760.900000
,3         David Brown   90636.000000   99699.600000
,4        Olivia Jones   82143.473684   90357.821053
,5        James Garcia   94268.000000  103694.800000
,6     Sophia Martinez   58141.000000   63955.100000
,7   Benjamin Anderson  111910.000000  123101.000000
,8    Charlotte Thomas   96044.000000  105648.400000
,10      Amelia Taylor   73827.000000   81209.700000
,11      Matthew Moore   95820.000000  105402.000000
,12       Isabella Lee  102623.000000  112885.300000
,13       Ethan Harris  115450.000000  126995.000000
,14          Mia Clark   62299.000000   68528.900000
,15    Alexander Lewis   83585.000000   91943.500000
,16      Harper Walker  104044.000000  114448.400000
,17       William Hall   82557.000000   90812.700000
,18       Eve

#### 3.3 Grouping, Summarization & Saving

In [62]:
# Grouped data by department
# total salary expense per department
dept_salary_total = df_new.groupby('Department')['Salary'].sum()
print("\nTotal salary expense per deparment:")
print(dept_salary_total)


,Total salary expense per deparment:
,Department
,Finance       294132.000000
,HR            311078.000000
,IT            142829.000000
,Marketing     194053.473684
,Operations    262463.000000
,Sales         331100.000000
,Name: Salary, dtype: float64


In [70]:
# new cleaned csv
df_new.to_csv('project1_part2_cleaned_data.csv', index=False)

In [12]:
# Histogram of Happiness Score
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(8, 5))
sns.histplot(df_new['Happiness Score'], kde=True, color='green')
plt.title('Distribution of Happiness Scores')
plt.xlabel('Happiness Score')
plt.ylabel('Frequency')
plt.show()


NameError: name 'df_new' is not defined

<Figure size 800x500 with 0 Axes>